### ISSUE TITLE
Compatibility issue with PyTorch Lightning >= 1.6.0

### ISSUE THREAD

**Issue by rasbt** [SkafteNicki/pl_crossvalidate#3]
Hey, I was just thinking about implementing k-fold support and saw this awesome library! Great work! Just wanted to drop you a note that I noticed that it currently doesn't work with PyTorch Lightning >= 1.6.0. It works fine with e.g., 1.5.10 but in 1.6.0 it throws an error when calling `trainer.cross_validate()`:
![Screen Shot 2022-05-04 at 11 04 17 AM](https://user-images.githubusercontent.com/5618407/166723699-2f4ddd10-9510-4eac-b107-ce623d73c2ad.png)
 
It happens in both cases whether you use a `datamodule` or `train_dataloader`.

**Comment by Xinheng-He** [comment]
I also meet this problem. Seems have no solution……

**Comment by SkafteNicki** [comment]
Hi,
I have revamped the package this weekend, so the package is now compatible with `lightning>=2.0`.
