### ISSUE TITLE
Create_ensemble issues in PL 1.5.10

### ISSUE THREAD

**Issue by rasbt** [SkafteNicki/pl_crossvalidate#4]
I noticed that there are also issues with the `create_ensemble` method complaining that the `model` argument is missing. I tried it with all possible settings providing a `model` only, providing checkpoints only, and providing a model and checkpoints. This issue occurs with PyTorch Lightning 1.5.10. I put together a self-contained example notebook here (https://github.com/rasbt/deeplearning-models/blob/master/pytorch-lightning_ipynb/kfold/kfold-light-cnn-mnist.ipynb) that reproduces the error if you uncomment the `create_model` code at the bottom.

**Comment by SkafteNicki** [comment]
Hi,
I have revamped the package this weekend, so the package is now compatible with `lightning>=2.0`.
Hopefully, whatever issue you were running into is solved now.

**Comment by rasbt** [comment]
That's awesome! Thanks!!
