### ISSUE TITLE
Not possible to install pl_cross with poetry

### ISSUE THREAD

**Issue by YerePhy** [SkafteNicki/pl_crossvalidate#5]
I'm having trouble installing pl_cross with poetry, I've open a [question in StackOverflow ](https://stackoverflow.com/questions/72770213/install-a-python-repo-from-setup-py-in-poetry/72777145#72777145)describing the problem.

**Comment by SkafteNicki** [comment]
Hi,
I have revamped the package this weekend, so it should now be possible to install with poetry now.
