### ISSUE TITLE
Val dataloader requirement

### ISSUE THREAD

**Issue by ncuxomun** [SkafteNicki/pl_crossvalidate#66]
Hi, thanks a lot for the pl_crossvalidate! I am trying to use but I keep running into some errors. The error I get is `TypeError: An invalid dataloader was returned from `KFoldDataModule.val_dataloader()`. Found None.` with `trainer.cross_validate(model, train_dataloader=ds_loader)`. 
The reason I go with train_dataloader is because I have a very small dataset and I cannot afford to split into train and val and and also num_folds. Do I need to have a val_dataloader in this case?

**Comment by ScarWar** [comment]
You can disable the validation step in `KFoldTrainer` by passing `limit_val_batches=0` during its initialization.

**Comment by ncuxomun** [comment]
Thanks! I will give it a try!
